### ISSUE TITLE
Website content disappears after importing “distance_calculator.ts”

### ISSUE THREAD

**Issue by Qusay99** [Qusay99/security-alert-for-safety#18]
`import {NearestCityCalculator} from '../distance_calculator';`
`let userCity = NearestCityCalculator.findNearestCity([49.4719058, 8.4852408]);`

After I've imported the module, as shown above, I tried to use the method `.findNearestCity()`. However, this resulted in disappearing all website content.
Then I started inspecting the “distance_calculator.ts” file more closely to find the error. This wasn't easy because no error message was shown.
## Alternativ for the request.get() method to import the JSON file 
I thought that the Request method for importing the JSON file was causing the error.

![image](https://user-images.githubusercontent.com/36747388/152764139-15dfd504-9f67-4b2d-a9fd-ddde0265f8b2.png)
so I looked for an alternative to import the JSON-file.

I found out that I could import the JSON-file using the fetch() module within the <script> element in the svelte component. 

So I implemented it as following:
![image](https://user-images.githubusercontent.com/36747388/152764695-94a26705-fa3b-4744-8fa7-c35cca7e43a3.png)

This made it possible to bypass the `request.get()` method within the TS-file.

Unfortunately, the problem was not solved completely.

## Error when importing a Deno module
After I continued examining the file line by line, I found out that the import of the external module called “DistanceCalculator” does not work and that the disability of importing deno modules the reason for the first error of the `request.get()` method mentioned above as well.

![image](https://user-images.githubusercontent.com/36747388/152783384-db9b6faa-1ced-46db-9b29-af65c1fedf5e.png)

Changing the extension of the deno module from .js to .ts did not work as expected.

Now I am trying to figure out how to fix the issue to be able to import  external deno modules.

**Comment by michael-spengler** [comment]
solution proposal: 
regenerate frontend / client / browser part using https://github.com/crewdevio/Snel#what-do-i-need-to-start-using-snel

--> with this you can use deno modules

**Comment by Qusay99** [comment]
issue solved
